services:
  pocket_db_setup:
    image: alpine/curl
    restart: "no"
    env_file:
      - .env
    entrypoint: >
      curl -X POST http://$DATABASE_URL:8080/api/admins --header 'Content-Type: application/json' -d '{"email": "'"$PB_ADMIN_USER"'", "password": "'"$PB_ADMIN_PASS"'", "passwordConfirm": "'"$PB_ADMIN_PASS"'"}'

  compute:
    build: ./compute
    ports:
      - "8000:8001"
    depends_on:
      - pocket_db_setup
    env_file:
      - .env
    volumes:
      - ./compute/api:/app/api
    entrypoint: uvicorn api.app:app --host 0.0.0.0 --port 8001 --reload

volumes:
  qdrant_data:
  pocket_data:
  audio_data: